apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-timer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: focus-timer
  template:
    metadata:
      labels:
        app: focus-timer
    spec:
      containers:
        - name: focus-timer
          image: 732168977482.dkr.ecr.us-east-1.amazonaws.com/focus-timer:latest #${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/focus-timer:latest
          ports:
            - containerPort: 80
