app: focus
replicas: 2
ECR_REGISTRY: 732168977482.dkr.ecr.us-east-1.amazonaws.com
IMAGE_TAG: 19

service:
  type: LoadBalancer
  port: 80
  target_port: 8080
  protocol: TCP

# Add these to satisfy the default NOTES.txt and other templates
ingress:
  enabled: false
httpRoute:
  enabled: false
autoscaling:
  enabled: false