apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-menu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-menu-app
  template:
    metadata:
      labels:
        app: restaurant-menu-app
    spec:
      containers:
        - name: restaurant-menu-app
          image: 732168977482.dkr.ecr.us-east-1.amazonaws.com/restaurant-menu-app:1
          ports:
            - containerPort: 80
