apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-journal-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: study-journal-app
  
  template:
    metadata:
      labels:
        app: study-journal-app
    
    spec:
      containers:
        - name: study-journal-app
    
          image: 732168977482.dkr.ecr.us-east-1.amazonaws.com/study-journal-app:4
          ports:
            - containerPort: 80
