name: restaurant-menu-app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: restaurant-menu-app
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # ---------------------------
      # AWS Auth (OIDC)
      # ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_OIDC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------------------
      # CREATE ECR REPOSITORY (NEW STEP)
      # ---------------------------
      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names ${{ env.IMAGE_NAME }} || \
          aws ecr create-repository \
            --repository-name ${{ env.IMAGE_NAME }} \
            --image-tag-mutability MUTABLE \
            --image-scanning-configuration scanOnPush=true

      # ---------------------------
      # Build Docker Image
      # ---------------------------
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./restaurant-menu-app/
          push: false
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

      # ---------------------------
      # Trivy Image Scan
      # ---------------------------
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          severity: CRITICAL,HIGH
          exit-code: 0
          ignore-unfixed: true

      # ---------------------------
      # Push to ECR
      # ---------------------------
      - name: Push image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: ./restaurant-menu-app/
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
            ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest


           # Setup Kubectl
    
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
         version: 'v1.29.0'


     #Create the Entry
      - name:
        run: |
         aws eks create-access-entry \
          --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
          --principal-arn ${{ secrets.AWS_ROLE_ARN_OIDC }} \
          --type STANDARD

     #Attach the Policy
    
      - name: Attach EKS Access Policy
        run: |
          aws eks create-access-entry \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --principal-arn ${{ secrets.AWS_ROLE_ARN_OIDC }} \
            --type STANDARD || echo "Access Entry already exists, skipping..."

        # Update kubeconfig (EKS)
  
      - name: Update kubeconfig
        run: |
         aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Verify Authentication
        run: |
          kubectl auth can-i create deployments --namespace restaurant

       # Deploy to EKS
       
      - name: Deploy to EKS
        run: |
          kubectl create namespace restaurant || true
          kubectl apply -f ./restaurant-menu-app/restaurant-deployment.yaml -n restaurant
          kubectl apply -f ./restaurant-menu-app/restaurant-service.yaml -n restaurant
          kubectl get all -n restaurant
